### get tutor
GET http://localhost:3000/tutor

### get pet
GET http://localhost:3000/pet

### get tutor com id
GET http://localhost:3000/tutor/2

### get pet com id
GET http://localhost:3000/pet/1

### adicionando via post
POST http://localhost:3000/tutor
Content-Type: application/json

{
  "id": 3,
  "name": "ivo",
  "phone": "987654321",
  "email": "ivoaragao@example.com",
  "date_of_birth": "1990-05-25 09:15",
  "zip_code": "123577",
  "pets": [
    {
      "id": 3,
      "name": "mucilom",
      "species": "dog",
      "carry": "p",
      "weight": 4,
      "date_of_birth": "2015-10-02 11:30"
    }
  ]
}

### alterando dados tutor via patch
PATCH  http://localhost:3000/tutor/1
Content-Type: application/json

        {
          "name":"jose",
          "phone":985185188
          
        }

### alterando dados pet via patch
PATCH http://localhost:3000/pet/1/tutor/1
Content-Type: application/json

  {
  "name": "stich",
  "species": "lobo",
  "carry": "g",
  "weight": 10,
  "date_of_birth": "01/01/2013"
}    

### deletando dados via id
DELETE http://localhost:3000/tutor/1
